version: '3'
services:
  backend:
    build:
      context: ./backend/
    command: nodemon bin/www
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    # env_file: ./api/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    # env_file: ./client/.env # TODO - uncomment this to auto-load your .env file!